# Generated by Django 5.1.4 on 2025-01-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('publication_date', models.CharField(max_length=8, verbose_name='Data de Publicação')),
                ('isbn', models.CharField(max_length=14, unique=True, verbose_name='ISBN')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
